NumPy Assignment Questions

Data Types & Attributes

1. Create a NumPy array arr of integers from 0 to 5 and print its data type.

In [8]:
import numpy as np
arr1 = np.array(list(map(int, input("Enter integers separated by space (0–5): ").split())))
print(arr1.dtype)

Enter integers separated by space (0–5):  0 1 2 3 4 5


int32


2. Given a NumPy array arr, check if its data type is float64.

In [11]:
arr2 = np.array(list(map(float, input("Enter float numbers: ").split())))
print(arr2.dtype == np.float64)

Enter float numbers:  1.1 2.2 3.3


True


3. Create a NumPy array arr with a data type of complex128 containing three
complex numbers.

In [14]:
arr3 = np.array([complex(x) for x in input("Enter 3 complex numbers (e.g., 1+2j 3+4j 5+6j): ").split()], dtype=np.complex128)
print(arr3)
print(arr3.dtype)

Enter 3 complex numbers (e.g., 1+2j 3+4j 5+6j):  1+2j 3+4j 5+6j


[1.+2.j 3.+4.j 5.+6.j]
complex128


4. Convert an existing NumPy array arr of integers to float32 data type.

In [16]:
arr4 = np.array(list(map(int, input("Enter integers: ").split())))
arr4 = arr4.astype(np.float32)
print(arr4)
print(arr4.dtype)

Enter integers:  10 20 30


[10. 20. 30.]
float32


5. Given a NumPy array arr with float64 data type, convert it to float32 to reduce
decimal precision.

In [22]:
arr5 = np.array(list(map(float, input("Enter float64 numbers: ").split())), dtype=np.float64)
arr5 = arr5.astype(np.float32)
print(arr5)

Enter float64 numbers:  1.123456789 2.987654321


[1.1234568 2.9876542]


6. Write a function array_attributes that takes a NumPy array as input and returns
its shape, size, and data type.

In [33]:
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype
r = int(input("Enter number of rows: "))
c = int(input("Enter number of columns: "))
arr = np.array([list(map(int, input(f"Enter {c} integers for row {i+1}: ").split())) for i in range(r)])
print(array_attributes(arr))

Enter number of rows:  2
Enter number of columns:  2
Enter 2 integers for row 1:  1 2 
Enter 2 integers for row 2:  31 21


((2, 2), 4, dtype('int32'))


7. Create a function array_dimension that returns the dimensionality of a NumPy
array.

In [35]:
def array_dimension(arr):
    return arr.ndim
arr = np.array(eval(input("Enter a nested list (e.g., [[1,2],[3,4]]): ")))
print(array_dimension(arr))

Enter a nested list (e.g., [[1,2],[3,4]]):  [[1,2],[3,4]]


2


8. Design a function item_size_info that returns the item size and total size in bytes
of a NumPy array.

In [37]:
def item_size_info(arr):
    return arr.itemsize, arr.nbytes
arr = np.array(list(map(int, input("Enter integers: ").split())), dtype=np.int32)
print(item_size_info(arr))

Enter integers:  10 20 30


(4, 12)


9. Create a function array_strides that returns the strides of the given NumPy array.

In [39]:
def array_strides(arr):
    return arr.strides
r = int(input("Enter number of rows: "))
c = int(input("Enter number of columns: "))
arr = np.array([list(map(int, input(f"Enter {c} integers for row {i+1}: ").split())) for i in range(r)], dtype=np.int32)
print(array_strides(arr))

Enter number of rows:  2
Enter number of columns:  2
Enter 2 integers for row 1:  1 2 
Enter 2 integers for row 2:  3 4


(8, 4)


10. Design a function shape_stride_relationship that returns the shape and
strides of the given array.

In [41]:
 def shape_stride_relationship(arr):
    return arr.shape, arr.strides
r = int(input("Enter number of rows: "))
c = int(input("Enter number of columns: "))
arr = np.ones((r, c), dtype=np.float64)
print(shape_stride_relationship(arr))

Enter number of rows:  3
Enter number of columns:  3


((3, 3), (24, 8))


Array Creation

11. Create a function create_zeros_array(n) to return a NumPy array of zeros with
n elements.

In [57]:
def create_zeros_array(n):
    return np.zeros(n)
n = int(input("Enter number of elements: "))
print(create_zeros_array(n))

Enter number of elements:  5


[0. 0. 0. 0. 0.]


12. Write a function create_ones_matrix(rows, cols) to create a 2D array filled
with ones.

In [55]:
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))
print(create_ones_matrix(rows, cols))

Enter number of rows:  2
Enter number of columns:  2


[[1. 1.]
 [1. 1.]]


13. Write a function generate_range_array(start, stop, step) to create a
ranged NumPy array.

In [50]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)
start = int(input("Enter start: "))
stop = int(input("Enter stop: "))
step = int(input("Enter step: "))
print(generate_range_array(start, stop, step))

Enter start:  2
Enter stop:  12
Enter step:  2


[ 2  4  6  8 10]
