NumPy Assignment Questions

Data Types & Attributes

1. Create a NumPy array arr of integers from 0 to 5 and print its data type.

In [8]:
import numpy as np
arr1 = np.array(list(map(int, input("Enter integers separated by space (0–5): ").split())))
print(arr1.dtype) 

Enter integers separated by space (0–5):  0 1 2 3 4 5


int32


2. Given a NumPy array arr, check if its data type is float64.

In [11]:
arr2 = np.array(list(map(float, input("Enter float numbers: ").split())))
print(arr2.dtype == np.float64)

Enter float numbers:  1.1 2.2 3.3


True


3. Create a NumPy array arr with a data type of complex128 containing three
complex numbers.

In [14]:
arr3 = np.array([complex(x) for x in input("Enter 3 complex numbers (e.g., 1+2j 3+4j 5+6j): ").split()], dtype=np.complex128)
print(arr3)
print(arr3.dtype)

Enter 3 complex numbers (e.g., 1+2j 3+4j 5+6j):  1+2j 3+4j 5+6j


[1.+2.j 3.+4.j 5.+6.j]
complex128


4. Convert an existing NumPy array arr of integers to float32 data type.

In [16]:
arr4 = np.array(list(map(int, input("Enter integers: ").split())))
arr4 = arr4.astype(np.float32)
print(arr4)
print(arr4.dtype)

Enter integers:  10 20 30


[10. 20. 30.]
float32


5. Given a NumPy array arr with float64 data type, convert it to float32 to reduce
decimal precision.

In [22]:
arr5 = np.array(list(map(float, input("Enter float64 numbers: ").split())), dtype=np.float64)
arr5 = arr5.astype(np.float32)
print(arr5)

Enter float64 numbers:  1.123456789 2.987654321


[1.1234568 2.9876542]


6. Write a function array_attributes that takes a NumPy array as input and returns
its shape, size, and data type.

In [33]:
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype
r = int(input("Enter number of rows: "))
c = int(input("Enter number of columns: "))
arr = np.array([list(map(int, input(f"Enter {c} integers for row {i+1}: ").split())) for i in range(r)])
print(array_attributes(arr))

Enter number of rows:  2
Enter number of columns:  2
Enter 2 integers for row 1:  1 2 
Enter 2 integers for row 2:  31 21


((2, 2), 4, dtype('int32'))


7. Create a function array_dimension that returns the dimensionality of a NumPy
array.

In [35]:
def array_dimension(arr):
    return arr.ndim
arr = np.array(eval(input("Enter a nested list (e.g., [[1,2],[3,4]]): ")))
print(array_dimension(arr))

Enter a nested list (e.g., [[1,2],[3,4]]):  [[1,2],[3,4]]


2


8. Design a function item_size_info that returns the item size and total size in bytes
of a NumPy array.

In [37]:
def item_size_info(arr):
    return arr.itemsize, arr.nbytes
arr = np.array(list(map(int, input("Enter integers: ").split())), dtype=np.int32)
print(item_size_info(arr))

Enter integers:  10 20 30


(4, 12)


9. Create a function array_strides that returns the strides of the given NumPy array.

In [39]:
def array_strides(arr):
    return arr.strides
r = int(input("Enter number of rows: "))
c = int(input("Enter number of columns: "))
arr = np.array([list(map(int, input(f"Enter {c} integers for row {i+1}: ").split())) for i in range(r)], dtype=np.int32)
print(array_strides(arr))

Enter number of rows:  2
Enter number of columns:  2
Enter 2 integers for row 1:  1 2 
Enter 2 integers for row 2:  3 4


(8, 4)


10. Design a function shape_stride_relationship that returns the shape and
strides of the given array.

In [41]:
 def shape_stride_relationship(arr):
    return arr.shape, arr.strides
r = int(input("Enter number of rows: "))
c = int(input("Enter number of columns: "))
arr = np.ones((r, c), dtype=np.float64)
print(shape_stride_relationship(arr))

Enter number of rows:  3
Enter number of columns:  3


((3, 3), (24, 8))


Array Creation

11. Create a function create_zeros_array(n) to return a NumPy array of zeros with
n elements.

In [57]:
def create_zeros_array(n):
    return np.zeros(n)
n = int(input("Enter number of elements: "))
print(create_zeros_array(n))

Enter number of elements:  5


[0. 0. 0. 0. 0.]


12. Write a function create_ones_matrix(rows, cols) to create a 2D array filled
with ones.

In [55]:
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))
print(create_ones_matrix(rows, cols))

Enter number of rows:  2
Enter number of columns:  2


[[1. 1.]
 [1. 1.]]


13. Write a function generate_range_array(start, stop, step) to create a
ranged NumPy array.

In [59]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)
start = int(input("Enter start: "))
stop = int(input("Enter stop: "))
step = int(input("Enter step: "))
print(generate_range_array(start, stop, step))

Enter start:  2
Enter stop:  10
Enter step:  2


[2 4 6 8]


14. Design a function generate_linear_space(start, stop, num) for equally
spaced values.

In [65]:
def generate_linear_space():
    start = float(input("Enter the start value: "))
    stop = float(input("Enter the stop value: "))
    num = int(input("Enter the number of values: "))
    result = np.linspace(start, stop, num)
    print("Linear Space:", result)
generate_linear_space()

Enter the start value:  2
Enter the stop value:  15
Enter the number of values:  5


Linear Space: [ 2.    5.25  8.5  11.75 15.  ]


15. Create a function create_identity_matrix(n) using numpy.eye.

In [77]:
def create_identity_matrix(n):
    return np.eye(n)
n = int(input("Enter size of identity matrix: "))
print(create_identity_matrix(n))

Enter size of identity matrix:  4


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


16. Write a function that converts a Python list into a NumPy array.

In [81]:
def convert_list_to_array(lst):
    return np.array(lst)
lst = eval(input("Enter a Python list (e.g., [1, 2, 3, 4]): "))
print(convert_list_to_array(lst))

Enter a Python list (e.g., [1, 2, 3, 4]):  [10, 20, 30]


[10 20 30]


17. Create a NumPy array and use numpy.view() to create a new view with the same
data.

In [83]:
arr = np.array(list(map(int, input("Enter array elements: ").split())))
view_arr = arr.view()
print("Original array:", arr)
print("View array:", view_arr)

Enter array elements:  1 2 3 4 5


Original array: [1 2 3 4 5]
View array: [1 2 3 4 5]


Concatenation and Stacking

18. Write a function to concatenate two NumPy arrays along a specified axis.

In [8]:
def concatenate_arrays():
    arr1 = input("Enter elements of first array (space-separated): ")
    arr2 = input("Enter elements of second array (space-separated): ")
    axis = int(input("Enter axis (0 for vertical, 1 for horizontal): "))
    a1 = np.array([int(x) for x in arr1.split()])
    a2 = np.array([int(x) for x in arr2.split()])
    if axis == 1:
        a1 = a1.reshape(1, -1)
        a2 = a2.reshape(1, -1)
    result = np.concatenate((a1, a2), axis=axis)
    print("Concatenated Array:\n", result)

19. Concatenate two arrays with different shapes horizontally using
numpy.concatenate.

In [16]:
import numpy as np
rows = int(input("Enter number of rows for array a: "))
a = []
print("Enter elements for array a (1 element per row):")
for _ in range(rows):
    a.append([int(input())])
a = np.array(a)
cols = int(input("Enter number of columns for array b: "))
b = list(map(int, input(f"Enter {cols} elements for 1 row of array b: ").split()))
b = np.array([b])
b_reshaped = np.repeat(b, rows, axis=0)
result = np.concatenate((a, b_reshaped), axis=1)
print("Concatenated Array:\n", result)

Enter number of rows for array a:  3


Enter elements for array a (1 element per row):


 1
 2
 3
Enter number of columns for array b:  2
Enter 2 elements for 1 row of array b:  4 5


Concatenated Array:
 [[1 4 5]
 [2 4 5]
 [3 4 5]]



20. Vertically stack multiple arrays from a list using numpy.vstack.

In [20]:
n = int(input("Enter number of arrays to stack: "))
arrays = []
for i in range(n):
    arr = list(map(int, input(f"Enter elements of array {i+1} (space-separated): ").split()))
    arrays.append(np.array(arr))
result = np.vstack(arrays)
print("\nOutput:")
print(result)

Enter number of arrays to stack:  3
Enter elements of array 1 (space-separated):  1 2
Enter elements of array 2 (space-separated):  2 3
Enter elements of array 3 (space-separated):  3 4



Output:
[[1 2]
 [2 3]
 [3 4]]


Array Generation

21. Write a function to generate an array of integers within a specified range (inclusive)
with a step.

In [31]:
start = int(input("Enter start value: "))
stop = int(input("Enter stop value (inclusive): "))
step = int(input("Enter step value: "))
result = np.arange(start, stop + 1, step)
print("\nOutput:")
print(result)

Enter start value:  2
Enter stop value (inclusive):  10
Enter step value:  2



Output:
[ 2  4  6  8 10]


22. Generate 10 equally spaced values between 0 and 1 using NumPy.

In [29]:
result = np.linspace(0, 1, 10)
print("\nOutput:")
print(result)


Output:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


23. Create 5 logarithmically spaced values between 1 and 1000.

In [33]:
result = np.logspace(0, 3, 5)
print("\nOutput:")
print(result)


Output:
[   1.            5.62341325   31.6227766   177.827941   1000.        ]


Pandas + NumPy

24. Create a Pandas DataFrame from a NumPy array with 5 rows and 3 columns of
random integers (1-100).

In [38]:
import pandas as pd
array = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(array, columns=['A', 'B', 'C'])
print("\nOutput:")
print(df)


Output:
    A   B   C
0  60   6  18
1  87  32  27
2  97  75   9
3  11  97  89
4  97  28  34


25. Write a function to replace all negative values in a specific column with zeros using
NumPy.

In [40]:
data = {
    'A': [5, -3, 7, -1],
    'B': [2, -6, -4, 9]
}
df = pd.DataFrame(data)
col = input("Enter column name to replace negatives with 0: ")
arr = df[col].values
arr[arr < 0] = 0
df[col] = arr
print("\nOutput:")
print(df)

Enter column name to replace negatives with 0:  B



Output:
   A  B
0  5  2
1 -3  0
2  7  0
3 -1  9


Indexing and Slicing

26. Access the 3rd element from the given NumPy array.

In [50]:
arr = np.array(list(map(int, input("Enter elements of the array (space-separated): ").split())))
print("\nOutput:")
print(arr[2])

Enter elements of the array (space-separated):  10 20 30 40 50



Output:
30


27. Retrieve the element at index (1, 2) from a 2D array.

In [52]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("\nOutput:")
print(arr[1, 2])


Output:
6



28. Extract elements greater than 5 using boolean indexing.

In [58]:
arr = np.array(list(map(int, input("Enter array elements (space-separated): ").split())))
print("\nOutput:")
print(arr[arr > 5])

Enter array elements (space-separated):  3 7 5 1 2



Output:
[7]



29. Slice elements from index 2 to 5 (inclusive) from a NumPy array.

In [60]:
arr = np.array(list(map(int, input("Enter array elements (space-separated): ").split())))
print("\nOutput:")
print(arr[2:6])

Enter array elements (space-separated):  10 12 14 56 45



Output:
[14 56 45]



30. Slice the sub-array [[2, 3], [5, 6]] from a 2D array.

In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nOutput:")
print(arr[0:2, 1:3])


Output:
[[2 3]
 [5 6]]
